events {}

http {
    server {
        listen 80;
<<<<<<< HEAD
=======

        location /users/ {
            proxy_pass http://user_service:8000/;
        }

        location /portfolio/ {
            proxy_pass http://portfolio_service:8000/;
        }
    }
}
>>>>>>> b201c40 (Save current working mobile app before UI professional upgrade)

        location /users/ {
            proxy_pass http://user_service:8000/;
        }

        location /portfolio/ {
            proxy_pass http://portfolio_service:8000/;
        }
    }
}
