events {}

http {

  server {
    listen 80;

    location /users/ {
      proxy_pass http://user_service:8000/;
    }

    location /portfolio/ {
      proxy_pass http://portfolio_service:8000/;
    }

  }

}
